version: "3"

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      frontend:
  database:
    image: postgres:15-alpine
    container_name: database
    volumes:
      - ./docker/data/database:/var/lib/postgresql/data
    env_file:
      - server/.env
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      backend:
  redis:
    image: redis:7-alpine
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    networks:
      backend:
  amqp:
    image: heidiks/rabbitmq-delayed-message-exchange:3.10.2-management
    container_name: amqp
    environment:
      - RABBITMQ_DEFAULT_USER=${AMQP_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${AMQP_PASSWORD}
    networks:
      backend:
  php:
    build: server
    container_name: php
    volumes:
      - ./docker/data/log:/srv/app/var/log
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AMQP_HOST=amqp
      - AMQP_PORT=5672
    depends_on:
      - database
      - redis
      - amqp
    networks:
      backend:
      frontend:

networks:
  frontend:
  backend: