version: "3.8"

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
      - "9001:9001"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${DEFAULT_SERVER_CRT}:/etc/ssl/default_server.crt
      - ${DEFAULT_SERVER_KEY}:/etc/ssl/default_server.key
    depends_on:
      - php
    networks:
      backend:
        ipv4_address: 172.16.1.253
      frontend:
        ipv4_address: 172.16.2.253
  database:
    image: postgres:15-alpine
    container_name: database
    volumes:
      - ./docker/data/database:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - TZ=Europe/Moscow
      - PGTZ=Europe/Moscow
    networks:
      backend:
        ipv4_address: 172.16.1.11
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    networks:
      backend:
        ipv4_address: 172.16.1.12
  amqp:
    image: heidiks/rabbitmq-delayed-message-exchange:3.10.2-management
    container_name: amqp
    environment:
      - RABBITMQ_DEFAULT_USER=${AMQP_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${AMQP_PASSWORD}
    networks:
      backend:
        ipv4_address: 172.16.1.13
  mqtt:
    image: iegomez/mosquitto-go-auth:2.0.0-mosquitto_2.0.14
    container_name: mqtt
    volumes:
      - ./docker/mosquitto/mosquitto.conf:/etc/mosquitto/mosquitto.conf
      - ./docker/mosquitto/conf.d:/mosquitto/conf.d
    networks:
      backend:
        ipv4_address: 172.16.1.14
  php:
    build:
      context: .
      args:
        TZ: Europe/Moscow
        COMPOSER_AUTH: ${COMPOSER_AUTH}
    container_name: php
    restart: always
    volumes:
      - ${DEFAULT_PUBLIC_KEY}:/etc/ssl/resource_key.key
      - ./docker/data/log:/srv/app/var/log
    environment:
      - DB_HOST=172.16.1.11
      - DB_PORT=5432
      - REDIS_HOST=172.16.1.12
      - REDIS_PORT=6379
      - AMQP_HOST=172.16.1.13
      - AMQP_PORT=5672
      - MQTT_HOST=172.16.1.14
      - MQTT_PORT=1883
    depends_on:
      - database
      - redis
      - amqp
      - mqtt
    networks:
      backend:
        ipv4_address: 172.16.1.10

networks:
  frontend:
    ipam:
      driver: default
      config:
        - subnet: 172.16.2.0/24
  backend:
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24